apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  labels:
    purpose: ingress
spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: ingress
      project: roboshop
      environment: dev
  template:
    metadata: 
      labels:
        purpose: ingress
        project: roboshop
        environment: dev
    spec:
      containers:
        - name: app-1
          image: yadaveshnithin/app-1:v1
        # - name: nginx
        #   image: nginx:stable-perl

---

apiVersion: v1
kind: Service
metadata:
  name: app-1
  labels:
    purpose: ingress
spec:
  selector:
    purpose: ingress
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-1
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:010666226306:certificate/a1ad0699-69f3-4183-846a-7c9fe479bf32
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: joindevops
spec:
  ingressClassName: alb
  rules:
  - host: "app-1.rshopsdaws84s.site"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app-1
            port:
              number: 80
  

